name: CMake Test on multiple platforms

on:
  pull_request:
    branches: ["main"]

jobs:
  check-if-files-changed:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.check.outputs.files_changed }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check if files have changed
        id: check
        run: |
          git fetch origin main
          changed_files=$(git diff --name-only origin/main..HEAD)
          echo "Files changed: $changed_files"
          if echo "$changed_files" | grep -E '\.(cpp|h|cmake)$|CMakeLists.txt'; then
            echo "files_changed=true" >> $GITHUB_ENV
          else
            echo "files_changed=false" >> $GITHUB_ENV
        shell: bash

  build:
    needs: check-if-files-changed
    runs-on: ${{ matrix.os }}
    if: ${{ env.files_changed == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug]
        include:
          - os: windows-latest
            cpp_compiler: cl
          - os: ubuntu-latest
            cpp_compiler: clang++
          - os: macos-latest
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}-${{ matrix.c_compiler }}
          path: ${{ steps.strings.outputs.build-output-dir }}

  conclusion:
    name: conclusion
    needs: [check-if-files-changed, build]
    runs-on: ubuntu-latest
    steps:
      - name: Result
        if: env.files_changed == 'false'
        run: |
          echo "No relevant files changed."
          exit 0

      - name: Result
        if: needs.build.result == 'success'
        run: |
          echo "Build and tests completed successfully."
          exit 0

      - name: Result
        if: needs.build.result != 'success'
        run: |
          echo "Build or tests failed."
          exit 1
