name: CMake Test on multiple platforms

on:
  pull_request:
    branches: ["main"]
    paths: ["**.cpp", "**.h", "**.cmake", "CMakeLists.txt"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug]
        include:
          - os: windows-latest
            cpp_compiler: cl
            install_packages_script: scripts/setup_packages.ps1
          - os: ubuntu-latest
            cpp_compiler: clang++
            install_packages_script: scripts/setup_packages.sh
          - os: macos-latest
            cpp_compiler: clang++
            install_packages_script: scripts/setup_packages.sh

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install packages on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: ./${{ matrix.install_packages_script }}

      - name: Install packages on Linux or MacOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          chmod +x ./${{ matrix.install_packages_script }}
          ./${{ matrix.install_packages_script }}

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}-${{ matrix.c_compiler }}
          path: ${{ steps.strings.outputs.build-output-dir }}
